# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='look',
        ),
    ]
