"""
Django settings for all project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^zehr=2l*29+-ekpc5v-ha_bawf4!8*+m&gze)#g12m^rrj6bd'

# SECURITY WARNING: don't run with debug turned on in production!

# 生产环境下设置
# DEBUG = False  # 未指定处理，则返回默认404页面；指定处理，则返回自定义错误处理页面。
# 非生产环境下设置
DEBUG = True

ALLOWED_HOSTS = ['*', ]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 安装news应用
    'news',
    # 安装model应用
    'model',
    # 安装view应用
    'view',
    # 安装tpl应用
    'tpl',
    # 安装deploy应用
    'deploy',
    # # 安装富文本编辑器
    # 'tinymce',
    # # 安装djcelery
    # 'djcelery',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # # 安装ip过滤中间件，黑名单
    # 'deploy.middleware.IpsForbidden',
    # # 中间件处理流程
    # 'deploy.middleware.MyCustomProcess',
    # # 中间件错误视图
    # 'deploy.middleware.MyCustomError',
)

ROOT_URLCONF = 'all.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'all.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'alls',
        'HOST': 'localhost',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'mysql',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# 非生产环境下配置
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# # 生产环境下配置
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# # 配置session数据库
# SESSION_ENGINE = 'redis_sessions.session'
# SESSION_REDIS_DB = 0
# SESSION_REDIS_HOST = 'localhost'
# SESSION_REDIS_PORT = 6379
# # SESSION_REDIS_PASSWORD = 'password'
# SESSION_REDIS_PASSWORD = ''
# SESSION_REDIS_PREFIX = 'session'

# 文件传输配置
MEDIA_ROOT = os.path.join(BASE_DIR, "static/media")

# # 富文本编辑器配置
# TINYMCE_DEFAULT_CONFIG = {
#     'theme': 'advanced',
#     # 'theme': 'simple',
#     'width': 600,
#     'height': 400,
#     'language': 'zh-CN',
#     'theme_advanced_buttons1': 'bold, italic, underline, strikethrough, justifyleft, justifycenter, justifyright, '
#                                'justifyfull, styleselect, bullist, numlist, outdent, indent, undo,redo, link, '
#                                'unlink, image, cleanup, help, code, table, row_before, row_after, delete_row, '
#                                'separator, rowseparator',
#     'theme_advanced_buttons2': 'col_before, col_after, delete_col, hr, removeformat, sub, sup, formatselect, '
#                                'fontselect, fontsizeselect, forecolor,charmap,visualaid,spacer,cut,copy,paste'
# }

# # 发送邮件配置
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.163.com'
# EMAIL_PORT = 25
# # 发送邮件的邮箱
# EMAIL_HOST_USER = 'lz15251847740@163.com'
# # 在邮箱中设置的客户端授权密码
# EMAIL_HOST_PASSWORD = 'qazwsx741852'
# # 收件人看到的发件人
# EMAIL_FROM = 'lumicie<lz15251847740@163.com>'

# celery配置
# 操作方式:
# python3 manage.py migrate
# python3 manage.py celery worker --loglevel=info

# import djcelery
# # 初始化
# djcelery.setup_loader()
# # 设置代理人的服务地址
# BROKER_URL = 'redis://127.0.0.1:6379/2'
# # 设置部署任务
# CELERY_IMPORTS = ('deploy.tasks', )
