# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30)),
                ('area_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.AreaInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=20)),
                ('book_read', models.IntegerField(default=0)),
                ('book_comment', models.IntegerField(default=0)),
                ('book_isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_comment', models.IntegerField(default=0)),
                ('book_read', models.IntegerField(default=0)),
                ('book_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=50)),
                ('hero_sex', models.BooleanField(default=True)),
                ('hero_desc', models.TextField()),
                ('hero_delete', models.BooleanField(default=False)),
                ('hero_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.BookInfo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.Dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='NewPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_address', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'my_custom_place',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('res_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=0)),
                ('activity', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Superman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gender', models.NullBooleanField(default=False)),
                ('desc', models.CharField(db_column='description', max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('age', models.IntegerField(default=0)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
