# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170319_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
