# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170321_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='click',
            new_name='click_number',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='heart_number',
            field=models.IntegerField(default=0),
        ),
    ]
