# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170325_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default='', verbose_name='正文-html'),
        ),
    ]
