# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_content_html'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
